name: Build ISO

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build-iso:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/build-iso-reusable.yml
    with:
      upload-artifact: true
      artifact-name: ubuntu-live-custom
      artifact-path: output/ubuntu-live-custom.iso
    secrets: inherit
