name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-iso:
    uses: ./.github/workflows/build-iso-reusable.yml
    with:
      upload-artifact: true
      artifact-name: ubuntu-live-custom
      artifact-path: output/ubuntu-live-custom.iso
    secrets: inherit
