name: Release ISO

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-iso-reusable.yml
    with:
      upload-artifact: true
      artifact-name: ubuntu-live-custom
      artifact-path: output/ubuntu-live-custom.iso
    secrets: inherit

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download ISO artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-live-custom
          path: output

      - name: Log in to GHCR
        if: startsWith(github.event.release.tag_name, 'v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up ORAS
        if: startsWith(github.event.release.tag_name, 'v')
        uses: oras-project/setup-oras@v1

      - name: Push ISO to GHCR
        if: startsWith(github.event.release.tag_name, 'v')
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          OWNER: ${{ github.repository_owner }}
        run: |
          OWNER_LC="${OWNER,,}"
          IMAGE="ghcr.io/${OWNER_LC}/ubuntu-live-custom"
          oras push "${IMAGE}:${TAG_NAME}" \
            --artifact-type application/vnd.iso.image \
            output/ubuntu-live-custom.iso:application/octet-stream
          oras tag "${IMAGE}:${TAG_NAME}" latest

      - name: Generate GHCR download instructions
        if: startsWith(github.event.release.tag_name, 'v')
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          OWNER_LC="${OWNER,,}"
          IMAGE="ghcr.io/${OWNER_LC}/ubuntu-live-custom"
          cat <<'EOF' > output/ubuntu-live-custom-ghcr.txt
          L'image ISO dépasse la limite 2 Go des assets GitHub Releases.
          Elle est publiée en tant qu'artéfact OCI via GHCR.
          
          Téléchargement :
          
          ```bash
          oras pull IMAGE_REF
          mv ubuntu-live-custom.iso output/ubuntu-live-custom.iso
          ```
          
          Remplacez `IMAGE_REF` par la référence OCI publiée (voir la section Downloads de la release).
          EOF
          sed -i "s|IMAGE_REF|${IMAGE}:${TAG_NAME}|" output/ubuntu-live-custom-ghcr.txt

      - name: Attach ISO to release
        if: !startsWith(github.event.release.tag_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          files: output/ubuntu-live-custom.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach GHCR instructions to release
        if: startsWith(github.event.release.tag_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          files: output/ubuntu-live-custom-ghcr.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
